"""Web Defender HTML presentation template."""
HTML_TEMPLATE = r'''<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Web Defender {{ app_version }}</title>
<style>
:root{--bg:#07111f;--panel:#0d1b2e;--panel2:#11243b;--line:#203a59;--text:#eaf2ff;--muted:#94a8c3;--white:#fff;--ink:#142033;--blue:#4d8dff;--green:#18b67a;--amber:#f2b84b;--red:#ef5b64;--soft:#f5f8fc}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#07111f,#091522 55%,#07111f);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text)}
.shell{max-width:1220px;margin:auto;padding:28px 20px 60px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.brand{display:flex;gap:12px;align-items:center}.logo{width:44px;height:44px;border:1px solid #31577e;border-radius:13px;display:grid;place-items:center;background:#102844;font-size:22px}.brand h1{font-size:22px;margin:0}.brand small{color:var(--muted)}.version{font-size:12px;color:#a8c3e6;border:1px solid var(--line);padding:7px 10px;border-radius:999px}
.search{background:#fff;border-radius:16px;padding:10px;display:flex;gap:10px;box-shadow:0 18px 50px #0005}.search input{flex:1;border:0;outline:0;padding:14px 15px;font-size:15px;color:#111827}.search button{border:0;background:#2468ed;color:#fff;font-weight:800;padding:0 22px;border-radius:11px;cursor:pointer}.loading{margin:18px 0;padding:15px;border:1px solid #2d5278;background:#0d2036;border-radius:12px;color:#bdd4ef}.hidden{display:none}
.hero[data-band="danger"]{border-color:#7f2f38;background:linear-gradient(135deg,#35151b,#161827)}.hero[data-band="high"]{border-color:#8a5524;background:linear-gradient(135deg,#322214,#121c2b)}.hero[data-band="guarded"]{border-color:#806a28}.hero[data-band="low"]{border-color:#2d6650}.hero[data-band="unverified"]{border-color:#536273}.hero[data-band="guarded_unverified"]{border-color:#806a28;background:linear-gradient(135deg,#2b2716,#10243a)}.hero{margin-top:18px;background:linear-gradient(135deg,#102945,#0b1d31);border:1px solid #294d73;border-radius:18px;padding:24px;display:grid;grid-template-columns:1fr 310px;gap:24px}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#8fb7ea;font-weight:800}.hero h2{font-size:30px;margin:8px 0}.hero p{color:#b7c9df;line-height:1.6;margin:0}.meters{display:grid;grid-template-columns:1fr 1fr;gap:10px}.meter{background:#071525;border:1px solid #294766;border-radius:13px;padding:14px}.meter span{font-size:11px;color:#9bb1ca;display:block}.meter b{font-size:24px;display:block;margin-top:5px}.meter small{color:#8298b2}.action{margin-top:15px;background:#0a1a2d;border-left:3px solid var(--blue);padding:12px 14px;border-radius:8px;color:#dce9f8}
.section{margin-top:18px}.section-title{display:flex;justify-content:space-between;align-items:end;margin-bottom:10px}.section-title h3{margin:0;font-size:17px}.section-title span{font-size:12px;color:var(--muted)}
.category-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.cat{background:#fff;color:var(--ink);border-radius:14px;padding:16px;min-height:142px;border:1px solid #dce6f2}.cat-head{display:flex;justify-content:space-between;gap:10px}.cat h4{margin:0;font-size:15px}.pill{font-size:11px;font-weight:800;padding:5px 8px;border-radius:999px;background:#edf2f7}.bar{height:7px;background:#e7edf5;border-radius:999px;margin:14px 0 10px;overflow:hidden}.bar i{display:block;height:100%;background:#5b8def;border-radius:999px}.cat strong{font-size:22px}.cat p{font-size:12px;color:#64748b;margin:7px 0 0;line-height:1.45}.cat.high .bar i,.cat.critical .bar i{background:var(--red)}.cat.medium .bar i{background:var(--amber)}.cat.low .bar i{background:var(--green)}
.evidence{background:#fff;color:var(--ink);border-radius:14px;padding:6px 18px}.ev{padding:14px 0;border-bottom:1px solid #e8eef5}.ev:last-child{border:0}.ev-top{display:flex;justify-content:space-between;gap:12px}.ev h4{margin:0;font-size:14px}.sev{font-size:10px;font-weight:900;text-transform:uppercase;padding:4px 7px;border-radius:999px;background:#edf2f7}.sev.critical,.sev.high{background:#fee2e2;color:#991b1b}.sev.medium{background:#fef3c7;color:#92400e}.sev.low{background:#dcfce7;color:#166534}.ev p{font-size:13px;color:#526176;margin:7px 0}.ev code{display:block;background:#0b1728;color:#cfe2ff;padding:9px;border-radius:7px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}
details.tech{margin-top:18px;border:1px solid #294d73;border-radius:14px;overflow:hidden;background:#0b1b2e}details.tech>summary{cursor:pointer;padding:16px 18px;font-weight:800;list-style:none;display:flex;justify-content:space-between}details.tech>summary small{font-weight:400;color:var(--muted)}.techbody{padding:0 14px 14px}.group{background:#fff;color:#152238;border-radius:12px;margin:10px 0;padding:15px}.group h4{margin:0 0 12px}.kv{display:grid;grid-template-columns:220px 1fr;gap:0}.kv b,.kv span{padding:8px;border-bottom:1px solid #e9eef5;font-size:12px}.kv b{color:#526176}.ok{color:#087a4e;font-weight:800}.warn{color:#a46500;font-weight:800}.bad{color:#b4232d;font-weight:800}.chips span{display:inline-block;margin:2px;padding:4px 7px;border-radius:6px;background:#edf3fa;font-size:11px}.feedback button{margin:4px;border:1px solid #cdd8e5;background:#fff;padding:7px 10px;border-radius:7px;cursor:pointer}
@media(max-width:850px){.hero{grid-template-columns:1fr}.category-grid{grid-template-columns:1fr}.meters{grid-template-columns:1fr 1fr}.kv{grid-template-columns:1fr}.top{align-items:flex-start}.brand small{display:none}}@media(max-width:520px){.search{flex-direction:column}.search button{padding:14px}.meters{grid-template-columns:1fr}.hero h2{font-size:24px}}
</style></head><body><div class="shell">
<div class="top"><div class="brand"><div class="logo">🛡️</div><div><h1>Web Defender</h1><small>Davranışsal web tehdit analizi</small></div></div><div class="version">{{ app_version }} • Render</div></div>
<div class="search"><input id="url" placeholder="Analiz edilecek URL'yi yapıştırın"><label style="display:flex;align-items:center;gap:7px;color:#172033;font-size:12px;font-weight:800;white-space:nowrap;padding:0 8px"><input id="feedOff" type="checkbox" checked style="width:16px;flex:0">Feed OFF test</label><button id="btn" onclick="analyze()">Derin Analiz</button></div>
<div id="loading" class="loading hidden">URL, ağ, tarayıcı, DOM, JavaScript, formlar ve davranış zincirleri inceleniyor…</div>
<div id="out" class="hidden">
<section class="hero"><div><div class="eyebrow">Analiz sonucu</div><h2 id="verdict">Sonuç hazırlanıyor</h2><p id="plain"></p><div class="action"><b>Ne yapmalıyım?</b><br><span id="action"></span></div></div><div class="meters"><div class="meter"><span>Tehdit kanıtı</span><b id="threat">-</b><small>0 düşük • 100 kritik</small></div><div class="meter"><span>Analiz kalitesi</span><b id="coverage">-</b><small>gözlemlenen yüzey</small></div><div class="meter"><span>Pasif risk</span><b id="passive">-</b><small>URL / domain</small></div><div class="meter"><span>Yapılandırma riski</span><b id="posture">-</b><small>site güvenlik ayarları</small></div><div class="meter"><span>Kimlik güveni</span><b id="identityTrust">-</b><small>tehdit skorunu düşürmez</small></div><div class="meter"><span>Kurumsal bağlam</span><b id="trustContext">-</b><small>RDAP • Tranco • DNS • ASN</small></div></div></section>
<section class="section"><div class="section-title"><h3>Karar kanalları</h3><span>Motor ve harici istihbarat birbirinden ayrıdır.</span></div><div class="category-grid" style="grid-template-columns:repeat(2,1fr)"><article class="cat"><div class="cat-head"><h4>Web Defender Motoru</h4><span class="pill" id="engineMode">-</span></div><strong id="engineScore">-</strong><p id="engineNote">Feed bağımsız motor sonucu.</p></article><article class="cat"><div class="cat-head"><h4>Harici İstihbarat</h4><span class="pill" id="intelMode">-</span></div><strong id="intelScore">-</strong><p id="intelNote">OpenPhish • PhishTank • URLhaus • ThreatFox</p></article></div></section>
<section class="section"><div class="section-title"><h3>Neyden şüphelendi?</h3><span>Yüzdeler olasılık değil, gözlenen kanıt gücüdür.</span></div><div id="cats" class="category-grid"></div></section>
<details class="tech" style="margin-top:18px"><summary>🧪 Motor Tanılama (V21) <small>HTTP → DOM → Identity → Trust Context → Fusion → Safety Gate</small></summary><div class="techbody"><div class="group"><pre id="diag" style="white-space:pre-wrap;word-break:break-word;font-size:11px;max-height:520px;overflow:auto">Tarama sonrası tanılama verisi burada görünür.</pre></div></div></details>
<details class="tech" id="credObsPanel"><summary>🔬 Credential Flow Observatory <small>V32.3.29 • ham sensör görünümü • skora katkı yapmaz</small></summary><div class="techbody"><div class="group"><div class="kv" id="credObsSummary"></div><h4 style="margin-top:16px">Ham gözlem</h4><pre id="credObs" style="white-space:pre-wrap;word-break:break-word;font-size:11px;max-height:720px;overflow:auto">Tarama sonrası credential-flow gözlemleri burada görünür.</pre></div></div></details>
<section class="section"><div class="section-title"><h3>Kanıtlar ve gerekçeler</h3><span>Motorun karar verirken gerçekten gördüğü şeyler</span></div><div id="evidence" class="evidence"></div></section>
<details class="tech"><summary>Teknik analiz raporunu aç <small>HTTP • Browser • DNS/TLS • DOM/JS • formlar • bulgular</small></summary><div class="techbody">
<div class="group"><h4>HTTP & Ağ</h4><div id="http" class="kv"></div></div>
<div class="group"><h4>Domain & TLS</h4><div id="domain" class="kv"></div></div>
<div class="group"><h4>Browser & Runtime</h4><div id="browser" class="kv"></div></div>
<div class="group"><h4>İçerik Edinme Motoru (V32.3.23)</h4><div id="acquisition" class="kv"></div></div>
<div class="group"><h4>Web İçeriği & Formlar</h4><div id="content" class="kv"></div></div>
<div class="group"><h4>Threat Intelligence</h4><div id="intel" class="kv"></div></div>
<div class="group"><h4>CVE / Teknoloji Eşleştirmesi</h4><div id="cves"></div></div>
<div class="group"><h4>Tüm teknik bulgular</h4><div id="allfindings"></div></div>
<div class="group feedback"><h4>Yerel öğrenme geri bildirimi</h4><div id="feedback"></div></div>
<div class="group"><h4>Fusion Trace / Karar DNA’sı (V32.3.10)</h4><pre id="fusiontrace" style="white-space:pre-wrap;word-break:break-word;font-size:11px;max-height:620px;overflow:auto"></pre></div>
<div class="group"><h4>Hatalar / eksik analiz yüzeyleri</h4><div id="errors"></div></div>
</div></details>
</div></div>
<script>
const esc=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const row=(a,b)=>`<b>${esc(a)}</b><span>${b}</span>`; const yes=x=>x?'<span class="ok">Evet</span>':'<span class="warn">Hayır</span>';
function catClass(s){return s>=75?'critical':s>=50?'high':s>=25?'medium':'low'}
function fmtEvidence(v){if(v===null||v===undefined||v==='')return '';if(Array.isArray(v))return v.map(fmtEvidence).filter(Boolean).join(' • ');if(typeof v==='object'){let keys=['evidence_id','canonical_event_id','expert_family','expert','modality','producer','source','group','family','title','description','detail','observation','reason','signal','value','target','destination','url'];let p=keys.filter(k=>v[k]!==undefined&&v[k]!==null&&v[k]!=='').map(k=>k+': '+fmtEvidence(v[k]));if(p.length)return p.join(' • ');try{return JSON.stringify(v)}catch(_e){return ''}}let t=String(v);return t.includes('[object Object]')?'Kanıt ayrıntısı yapılandırılmış veri olarak alındı; teknik EV kayıtlarına bakın.':t}
async function analyze(){let u=document.getElementById('url').value.trim();if(!u)return;document.getElementById('loading').classList.remove('hidden');document.getElementById('out').classList.add('hidden');document.getElementById('btn').disabled=true;try{let r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u,feed_off:document.getElementById('feedOff')?.checked===true})});let raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch(_e){d={error:`Sunucu geçerli JSON döndürmedi (HTTP ${r.status}).`}}if(!r.ok||d.error)throw new Error(d.error||`Analiz başarısız (HTTP ${r.status})`);if(!raw)throw new Error('Sunucudan boş analiz yanıtı geldi.');render(d)}catch(e){alert(e.message)}finally{document.getElementById('loading').classList.add('hidden');document.getElementById('btn').disabled=false}}
function render(d){document.getElementById('out').classList.remove('hidden');let a=d.defender?.assessment||{},p=a.primary||{},uv=d.ui_verdict_v32361||{};let hero=document.querySelector('.hero');if(hero)hero.dataset.band=uv.band||'';document.getElementById('verdict').textContent=uv.label||d.risk_level||'Sonuç';document.getElementById('plain').textContent=a.plain_summary||'Analiz tamamlandı.';document.getElementById('action').textContent=a.action||'-';let t=d.scores?.threat;document.getElementById('threat').textContent=t==null?'N/A':t+'/100';let cv=d.coverage_v19||{};document.getElementById('coverage').textContent=cv.quality||'Sınırlı';document.querySelector('#coverage + small').textContent=(cv.observed_percent??0)+'% yüzey gözlemlendi';document.getElementById('passive').textContent=(d.scores?.passive_risk??0)+'/100';let sp=d.scores?.security_posture;document.getElementById('posture').textContent=sp==null?'N/A':sp+'/100';let it=d.identity_trust_v21||{};document.getElementById('identityTrust').textContent=(it.score??0)+'/100';let tc=d.trust_context_v21||{};document.getElementById('trustContext').textContent=(tc.score??0)+'/100';
let dc=d.decision_channels_v32320||{},eng=dc.web_defender_engine||{},ext=dc.external_intelligence||{};document.getElementById('engineScore').textContent=eng.score==null?'N/A':eng.score+'/100';document.getElementById('engineMode').textContent=dc.mode==='FEED_OFF_TEST'?'FEED OFF • karar yetkili':'Birleşik mod';document.getElementById('engineNote').textContent=dc.mode==='FEED_OFF_TEST'?'Harici feed puanları bu skora ve karara sıfır katkı verir.':'Motor kanıtları ve savunma katmanları birlikte çalışır.';document.getElementById('intelScore').textContent=(ext.score??0)+'/100';document.getElementById('intelMode').textContent=ext.match?'Eşleşme var':'Eşleşme yok';document.getElementById('intelNote').textContent=(ext.sources||[]).length?('Kaynaklar: '+ext.sources.join(', ')):'Harici kaynaklarda eşleşme gözlenmedi.';
let cats=(a.categories||[]);document.getElementById('cats').innerHTML=cats.map(c=>`<article class="cat ${catClass(c.score)}"><div class="cat-head"><h4>${esc(c.name)}</h4><span class="pill">${esc(c.level)}</span></div><div class="bar"><i style="width:${Math.min(100,c.score)}%"></i></div><strong>${c.score}/100</strong><p>${c.evidence?.length?esc(c.evidence[0].title):(c.score>0?'Kategori skoru var ancak açıklayıcı kanıt zinciri yayımlanamadı.':'Bu kategoride belirgin kanıt bulunmadı.')}</p></article>`).join('');
let ev=a.evidence||[];document.getElementById('evidence').innerHTML=ev.length?ev.map(x=>`<article class="ev"><div class="ev-top"><h4>${esc(x.type)} • ${esc(x.title)}</h4><span class="sev ${esc(x.severity)}">${esc(x.severity)}</span></div><p>${esc(x.description)}</p>${x.evidence?`<code>${esc(fmtEvidence(x.evidence))}</code>`:''}</article>`).join(''):'<article class="ev"><h4>Belirgin tehdit kanıtı bulunmadı</h4><p>Motor analiz ettiği yüzeylerde karar değiştirecek bir davranış zinciri görmedi.</p></article>';
let co=d.credential_deep_observatory_v32328||{};let cos=document.getElementById('credObsSummary');if(cos){let st=co.static||{},rr=co.rendered||{},cmp=co.comparison||{},ph=co.pipeline_handoff||{};cos.innerHTML=row('Miss stage',esc(co.miss_stage||'-'))+row('Static input',esc(st.inputs??0)+' (identity '+esc(st.identity??0)+', secret '+esc(st.secret??0)+')')+row('Rendered input',esc(rr.inputs??0)+' (identity '+esc(rr.identity??0)+', secret '+esc(rr.secret??0)+')')+row('Frame input',esc((rr.frame_identity??0)+(rr.frame_secret??0)))+row('Handler görüldü',yes(cmp.handler_seen))+row('Sink görüldü',yes(cmp.sink_seen))+row('Static credential source',yes(ph.static_credential_source))+row('External sensitive form',esc(ph.static_external_sensitive_forms??0))+row('Proven source→sink edge',esc(ph.static_proven_edges??0))+row('Independent phishing',esc(ph.independent_phishing_score??0)+'/100')+row('Canonical credential',esc(ph.canonical_credential_score??0)+'/100')+row('Canonical phishing',esc(ph.canonical_phishing_score??0)+'/100')+row('State snapshots',esc((co.stateful_surface?.snapshots||[]).length))+row('App surface verified',yes(co.stateful_surface?.application_surface_verified))+row('Interaction gate',yes(co.stateful_surface?.interaction_gate_suspected))+row('Surface reason',esc(co.stateful_surface?.reason||'-'));}let cop=document.getElementById('credObs');if(cop)cop.textContent=JSON.stringify(co,null,2);
let h=d.http||{};document.getElementById('http').innerHTML=row('İstenen URL',esc(d.analyzed_url))+row('Final URL',esc(d.final_url))+row('HTTP',esc(h.status_code??'-')+' '+esc(h.reason||''))+row('Yönlendirme',esc(h.redirect_count??0)+' adet')+row('HTTPS ulaşıldı',yes(h.https_reached))+row('Analiz modu',esc(h.network_mode||'-'))+row('Karar',esc(h.decision||'-'));
let di=d.domain_info||{},ss=d.ssl_info||{};document.getElementById('domain').innerHTML=row('Hostname',esc(di.hostname||'-'))+row('Root domain',esc(di.root_domain||'-'))+row('IP adresleri',esc((di.ips||[]).join(', ')||'-'))+row('TLS geçerli',yes(ss.valid))+row('TLS sürümü',esc(ss.version||'-'))+row('Sertifika bitişi',esc(ss.not_after||'-'));
let b=d.browser||{};document.getElementById('browser').innerHTML=row('Browser denendi',yes(b.attempted))+row('Browser başarılı',yes(b.success))+row('Final URL',esc(b.final_url||'-'))+row('Başlık',esc(b.title||'-'))+row('DOM boyutu',esc(b.dom_length??0)+' karakter')+row('Ağ istekleri',esc((b.requests||[]).length))+row('Engellenen istek',esc((b.blocked_requests||[]).length))+row('Runtime kararı',esc(b.decision||'-'));
let ac=d.content_acquisition_v32316||{};document.getElementById('acquisition').innerHTML=row('Durum',esc(ac.display_name||ac.state||'-'))+row('HTTP gerçek gövde',yes(ac.http_body_observed))+row('Browser gerçek DOM',yes(ac.browser_body_observed))+row('Gözlenen byte',esc((ac.bytes_observed||0)+(ac.dom_bytes_observed||0)))+row('Kör noktalar',esc((ac.blind_spots||[]).join(', ')||'Yok'))+row('Recovery',esc(ac.recovery?.attempted?(ac.recovery?.adopted?'Başarılı':'Denenmiş / başarısız'):'Gerekmedi'));
let sem=b.semantic_dom||{},forms=b.forms||d.forms||[],frames=b.frames||d.iframes||[];document.getElementById('content').innerHTML=row('Form sayısı',esc(forms.length))+row('Iframe sayısı',esc(frames.length))+row('Input sayısı',esc((sem.inputs||[]).length))+row('Runtime hooks',esc(Object.values(b.runtime_hooks||{}).reduce((n,x)=>n+(Array.isArray(x)?x.length:0),0)))+row('Şüpheli JS pattern',esc((d.suspicious_patterns||[]).length))+row('İndirme bağlantısı',esc((d.downloads||[]).length));
let ti=d.threat_intelligence||{};document.getElementById('intel').innerHTML=row('Kontrol edildi',yes(ti.checked))+row('Kaynaklar',esc((ti.sources||[]).map(x=>x.name+': '+x.status).join(', ')||'-'))+row('IOC eşleşmeleri',esc((ti.matches||[]).map(x=>x.source+' / '+x.type).join(', ')||'Yok'))+row('Kaynak hataları',esc((ti.errors||[]).length));let ci=d.cve_intelligence||{};document.getElementById('cves').innerHTML=(ci.candidates||[]).length?(ci.candidates||[]).map(x=>`<div class="ev"><h4>${esc(x.cve)} • ${esc(x.product)} ${esc(x.version)}</h4><p>${esc(x.description)}</p><code>Aday eşleşme; sürüm/parmak izi doğrulanmadan açık kesinleşmiş sayılmaz.</code></div>`).join(''):'<div class="ev"><p>Doğrulanabilir ürün+sürüm parmak izi yoksa CVE ataması yapılmaz.</p></div>';
let fs=d.findings||[];document.getElementById('allfindings').innerHTML=fs.length?fs.map(x=>`<div class="ev"><div class="ev-top"><h4>${esc(x.title)}</h4><span class="sev ${esc(x.severity)}">${esc(x.severity)}</span></div><p>${esc(x.description)}</p>${x.evidence?`<code>${esc(fmtEvidence(x.evidence))}</code>`:''}</div>`).join(''):'Bulgu yok.';
let sid=d.scan?.scan_id||'';document.getElementById('feedback').innerHTML=`Bu sonucu doğrulayarak yerel modele eğitim örneği ekleyebilirsiniz.<br><button onclick="fb('${esc(sid)}','safe')">Güvenli</button><button onclick="fb('${esc(sid)}','phishing')">Phishing</button><button onclick="fb('${esc(sid)}','malware')">Malware</button><button onclick="fb('${esc(sid)}','suspicious')">Şüpheli</button>`;let dg=document.getElementById('diag');if(dg)dg.textContent=JSON.stringify(d.diagnostics_v19_1||{},null,2);let ft=document.getElementById('fusiontrace');if(ft)ft.textContent=JSON.stringify(d.fusion_trace_v32310||{},null,2);let er=d.errors||[];document.getElementById('errors').innerHTML=er.length?er.map(x=>`<div class="ev"><h4>${esc(x.module)}</h4><code>${esc(x.error)}</code></div>`).join(''):'Analiz modülleri hatasız tamamlandı.'}
async function fb(id,v){let r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scan_id:id,verdict:v})});let d=await r.json();alert(d.ok?'Geri bildirim kaydedildi.':(d.error||'Kaydedilemedi.'))}
</script></body></html>'''
